theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlo1"
ssid = true
speed_up = false
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max"
chip = "*-isa-*"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
